create database QuanLyThuVien
go
use QuanLyThuVien
go
--Tao Bang TacGia
CREATE TABLE TacGia
(
	MATG INT IDENTITY PRIMARY KEY,
	TENTG NVARCHAR(50),
	DIACHI NVARCHAR(50),
	GHICHU NVARCHAR(100) default null
)
go
CREATE TABLE LinhVuc
(
	MALV INT IDENTITY PRIMARY KEY,
	TENLV NVARCHAR(50),
	GHICHU NVARCHAR(100) default null
)
GO
CREATE TABLE NhaXB
(
	MANXB INT IDENTITY PRIMARY KEY,
	TENNXB NVARCHAR(50),
	DIACHI NVARCHAR(100),
	SODT NVARCHAR(20),
	GHICHU NVARCHAR(100) default null
)
GO
CREATE TABLE Sach
(
	MASACH INT NOT NULL IDENTITY PRIMARY KEY,
	TENSACH NVARCHAR(50),
	MATG INT REFERENCES TacGia(MATG),
	MANXB INT REFERENCES NhaXB(MANXB),
	MALV INT REFERENCES LinhVuc(MALV),
	NAMXB DATE,
	SOLUONG INT DEFAULT 0,
	NGAYNHAP DATE,
	GHICHU NVARCHAR(100) default null
)
GO

CREATE TABLE DocGia
(
	MADG INT IDENTITY PRIMARY KEY,
	TAIKHOAN NVARCHAR(100),
	MATkHAU NVARCHAR(100),
	HOTEN NVARCHAR(100),
	NGAYSINH date,
	GIOITINH bit,
	LOP NVARCHAR(100),
	DIACHI NVARCHAR(100),
	EMAIL NVARCHAR(100),
	GHICHU NVARCHAR(100) default null
)
GO

CREATE TABLE TaiKhoan
(
	TAIKHOAN NVARCHAR(100)NOT NULL,
	MATKHAU NVARCHAR(100)NOT NULL,
	TEN NVARCHAR(100),
	DIACHI NVARCHAR(100),
	EMAIL NVARCHAR(100),
	SODT NVARCHAR(100),
	NGAYSINH date,
	GIOITINH bit
)
GO
CREATE TABLE MuonSach
(
	MADG INT REFERENCES DocGia(MADG),
	MASACH INT REFERENCES Sach(MASACH),
	SOPHIEUMUON INT IDENTITY PRIMARY KEY,
	NGAYMUON DATE,
	NGAYTRA DATE,
	XACNHANTRA INT DEFAULT 0, -- 0 LA CHUA TRA --1 DA TRA
	GHICHU NVARCHAR(100) default null
)

GO
--select * from TaiKhoan where TAIKHOAN = N'Linh' and MATKHAU = N'1'
--INSERT TAIKHOAN
INSERT INTO TaiKhoan(TAIKHOAN, MATKHAU, TEN, DIACHI, EMAIL, SODT,NGAYSINH,GIOITINH) VALUES (N'Linh',N'1', N'Khánh Linh', N'01, Phù Đổng Thiên Vương, P9, Đà Lạt', N'linh1475@gmail.com', N'01445554444',GETDATE(),1)
INSERT INTO TaiKhoan(TAIKHOAN, MATKHAU, TEN, DIACHI, EMAIL, SODT,NGAYSINH,GIOITINH) VALUES (N'Staff',N'1', N'Staff', N'01, Phù Đổng Thiên Vương, P9, Đà Lạt', N'staff@gmail.com', N'0144588944',GETDATE(),1)
GO
--INSERT LINHVUC
INSERT INTO LinhVuc(TENLV) VALUES (N'Khoa Học')
INSERT INTO LinhVuc(TENLV) VALUES (N'Tài Liệu Học tập')
INSERT INTO LinhVuc(TENLV) VALUES (N'Ngoại Ngữ')
INSERT INTO LinhVuc(TENLV) VALUES (N'Triết Học')
go
--INSERT NHAXB
INSERT INTO NhaXB(TENNXB,DIACHI,SODT) VALUES (N'Nhà xuất bản Kim Đồng',N'Ai biết',N'4567788899')
INSERT INTO NhaXB(TENNXB,DIACHI,SODT) VALUES (N'Nhà xuất bản giáo dục',N'Ai biết',N'8888881111')
INSERT INTO NhaXB(TENNXB,DIACHI,SODT) VALUES (N'Nhà xuất bản lao động',N'Ai biết',N'8888833333')
GO
--INSERT TACGIA
INSERT INTO TacGia(TENTG,DIACHI) VALUES (N'Xuân Quỳnh',N'Ai biết')
INSERT INTO TacGia(TENTG,DIACHI) VALUES (N'Hồ Chí Minh',N'Ai biết')
INSERT INTO TacGia(TENTG,DIACHI) VALUES (N'Đoán Xem',N'Ai biết')
GO
--INSERT SACH
INSERT INTO Sach(TENSACH,MATG,MANXB,MALV, NAMXB,SOLUONG,NGAYNHAP) VALUES (N'Chính trị Mác - Lênin', 2, 2, 4, GETDATE(), 10, GETDATE())
INSERT INTO Sach(TENSACH,MATG,MANXB,MALV, NAMXB,SOLUONG,NGAYNHAP) VALUES (N'Tiếng Anh Giao Tiếp', 1, 2, 3, GETDATE(), 10, GETDATE())
INSERT INTO Sach(TENSACH,MATG,MANXB,MALV, NAMXB,SOLUONG,NGAYNHAP) VALUES (N'Kỹ năng soạn thảo văn bản', 3, 1, 2, GETDATE(), 10, GETDATE())
INSERT INTO Sach(TENSACH,MATG,MANXB,MALV, NAMXB,SOLUONG,NGAYNHAP) VALUES (N'Nhập môn công nghệ thông tin', 1, 3, 1, GETDATE(), 10, GETDATE())
GO
--INSERT DOCGIA
INSERT INTO DocGia(TAIKHOAN, MATKHAU, HOTEN, NGAYSINH, GIOITINH, LOP, DIACHI, EMAIL) VALUES (N'docgia1',N'1',N'Nguyễn Khánh Linh', GETDATE(), 1, N'CTK42', N'Ai Biết',N'linh14751@gmail.com')
INSERT INTO DocGia(TAIKHOAN, MATKHAU, HOTEN, NGAYSINH, GIOITINH, LOP, DIACHI, EMAIL) VALUES (N'docgia2',N'1',N'Lê Nhật Ánh',  GETDATE(), 1, N'CTK42', N'Ai Biết',N'nhatanh@gmail.com')
go
--INSERT MUONSACH
INSERT INTO MuonSach(MADG, MASACH, NGAYMUON, NGAYTRA, XACNHANTRA) VALUES (1,2,GETDATE(),GETDATE(),0)
INSERT INTO MuonSach(MADG, MASACH, NGAYMUON, NGAYTRA, XACNHANTRA) VALUES (2,3,GETDATE(),GETDATE(),0)
INSERT INTO MuonSach(MADG, MASACH, NGAYMUON, NGAYTRA, XACNHANTRA) VALUES (2,3,GETDATE(),GETDATE(),1)

GO
select* from  DocGia 
select* from  LinhVuc
select* from  MuonSach
select* from  TaiKhoan
select* from  NhaXB
select* from  Sach
select* from  TacGia
GO
--Login
CREATE PROC USP_Login
@account nvarchar(100), @password nvarchar(100)
as
begin
	select * from TaiKhoan where TAIKHOAN = @account and MATKHAU = @password
end
go
--exec USP_Login N'staff' , N'2'
go
--select * from TaiKhoan where QUYENHAN = 1
--update TaiKhoan set NGAYSINH = GETDATE() , GIOITINH = N'Nam' where TaiKhoan = N'Staff'

--insert TaiKhoan(TAIKHOAN,MATKHAU,TEN,DIACHI,EMAIL,SODT,NGAYSINH,GIOITINH) values(N'linh',N'1',N'Nguyễn Khánh Linh',N'Nguyen Du, P9',N'linh@gmail.com',N'0776598805',2000-10-08,N'Nam')
--update TaiKhoan set	MATKHAU = N'1' where TaiKhoan = N'linh'
select * from TaiKhoan where TaiKhoan = N'linh' and MatKhau = N'1'
