CREATE DATABASE QuanLyBangDia
GO
USE QuanLyBangDia
GO
-- Thể Loại
CREATE TABLE TheLoai 
(
	MaTL INT IDENTITY PRIMARY KEY NOT NULL, 
	TenTL NVARCHAR(100)
)
GO
--Băng Đĩa
CREATE TABLE BangDia 
(
MaBD INT IDENTITY PRIMARY KEY, 
TenBD NVARCHAR(100), 
SoLuong INT NOT NULL, 
DonGia INT NOT NULL, 
MaTL INT REFERENCES TheLoai(MATL)
)
GO
--Khách hàng
CREATE TABLE KhachHang 
(
MaKH INT IDENTITY PRIMARY KEY, 
TenKH NVARCHAR(100), 
SoDT NVARCHAR(100), 
DiaChi NVARCHAR(100)
)
GO
--Thuê
CREATE TABLE Thue 
(
Luot INT IDENTITY PRIMARY KEY, 
MaBD INT REFERENCES BangDia(MaBD), 
MAKH INT REFERENCES KhachHang(MaKH),
TienCoc int, 
NgayBD date,
NgayTra date
)
GO
SELECT * FROM TheLoai
SELECT * FROM KhachHang
SELECT * FROM BangDia
SELECT * FROM Thue

